### PR TITLE
Adding folders, and a REST Setup workflow

### PR DESCRIPTION
**Pull request by eshanks16**
More to come for vRA7

### CODE REVIEW

**Comment by chriswahl** [comment]
@eshanks16 @mattaltimar Is this still a valid PR? Should it be merged or closed?

**Comment by eshanks16** [comment]
There are now two pull requests. The first one can be ignored. The second one is the newly refactored code.

**Comment by mattaltimar** [comment]
Thank Eric!  Trying to load this into a 6.0.2 enviornment and I'm getting a
bunch of "unable to import" messages.  Is this only going to be compatible
with vRO 7?  These appear to be standard library objects that you included
in your custom package?

[image: Inline image 1]

**Comment by eshanks16** [comment]
Yes, this was done in vRO 7. Perhaps there is an issue with changing between versions.

**Comment by mattaltimar** [comment]
Ok,we may need to keep both packages to support older versions of vCO.
I'll play around with it more and see if I can get it working in 6.0.2

Matt

**Comment by eshanks16** [comment]
It doesn't help you much, but I did import it from one vRO 7 to another and that worked. That included using the embedded appliance --> stand alone, but they were version7 for both.

**Comment by mattaltimar** [comment]
Yeah, I don't get those errors in vRO 7 either

**Comment by eshanks16** [comment]
Just an FYI, I imported the package into a 6.0.3 repo of ours today without error. Not sure if that helps or not.

**Comment by mattaltimar** [comment]
Ok, I'm going to stand up 6.0.3 to test.  We do have at least 1 customer
running 6.0.2, so hopefully they are willing to upgrade if this works on
6.0.3

**Comment by mattaltimar** [comment]
I just stood up a vanilla 6.0.3 and get the same result with several items
in the package.

[image: Inline image 1]

[image: Inline image 2]

**Comment by mattaltimar** [comment]
I'm not running into any problems running the workflows, so I'm not sure
what those additional components are.  I may just regenerate the package
from 6.0.2 and see if it can be imported into future versions without that
issue.  I will test all functionality first in 6.0.2 though.

**Comment by eshanks16** [comment]
AH! so here's the deal. The elements that are failing to import are the out of the box workflows/actions from VMware. So if they ever update them the package won't import them again. I don't think its an issue because the new elements "SHOULD" work still. However, if you're worried about this, then just clone those elements and change the workflows to use the "cloned" elements instead. That way when you import it will be totally different elements from the Out of Box stuff.

**Pull request closed without merging**
